import React from 'react'
import { useNavigate } from 'react-router-dom'
const About = () => {
    const navigate = useNavigate()
  return (
    <div>this is made by ashwinithebest 
      <button type="button" onClick={()=>navigate(-1)} className="btn btn-secondary create g-col-4 m-2" >Go Back</button>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In tempor posuere ex, sit amet elementum erat sodales at. Etiam gravida sollicitudin massa eget faucibus. Nulla ac ornare ante, ut dictum sem. Donec imperdiet sem efficitur nisl vestibulum laoreet. Nam sagittis rutrum dolor, nec blandit urna accumsan at. Pellentesque fringilla at lorem id ullamcorper. Nulla diam quam, placerat at tempor sed, ultricies a orci. Vivamus non iaculis turpis, quis semper quam.

Ut diam turpis, lobortis ut dolor at, ultricies sodales ligula. Curabitur et mi id justo interdum elementum. Donec ut dui vitae mauris mollis accumsan. Fusce a dictum purus, vitae finibus est. Quisque et tristique ipsum. Fusce consequat eros vel mi sagittis fringilla. Quisque scelerisque dolor id felis rutrum laoreet. Duis imperdiet tempor mauris a dictum. Aenean tortor justo, imperdiet sit amet convallis vel, pharetra id libero. Ut iaculis urna risus, vel rhoncus risus iaculis placerat. Fusce at arcu ac est dictum sagittis. Maecenas pellentesque consectetur dui, rutrum condimentum mi ullamcorper et. In rutrum non mi sit amet pellentesque. Nullam hendrerit mollis metus, in malesuada quam mollis suscipit. Sed efficitur tellus in vehicula hendrerit.

Sed vel metus augue. Cras lobortis orci ut elementum vulputate. Mauris lobortis fermentum erat a rutrum. Phasellus commodo euismod lacus in ultricies. Integer vel odio justo. Proin mollis arcu quis pellentesque blandit. Aliquam in euismod purus. Nullam sagittis ornare mi, lacinia porta nibh lobortis vitae. Etiam vel tincidunt quam, vel lobortis purus.

Proin fringilla a arcu lobortis tincidunt. Duis tempor mattis rutrum. Maecenas at tempus mi. Duis congue volutpat ligula, quis lobortis mi ultrices eu. Nulla ornare, lacus non aliquet malesuada, tortor turpis semper enim, sit amet semper augue lorem id augue. Quisque lobortis dolor eget luctus sollicitudin. Proin purus risus, viverra ut fringilla vitae, tincidunt eu nunc. Nulla lorem enim, blandit in tortor eget, rutrum auctor nunc. Aenean ut dui sit amet tellus fermentum rutrum id vitae augue. Fusce venenatis, quam eget mollis commodo, nisl ante ornare orci, ac sodales quam metus ut nibh. Duis elementum porta nulla, sed volutpat eros tincidunt ut. Etiam malesuada odio a posuere maximus.

Sed varius dictum porttitor. Curabitur vitae lorem vel erat viverra porta non at quam. Pellentesque lacinia eros a bibendum sollicitudin. Fusce ut risus nibh. Sed ultrices vel tellus eget condimentum. Praesent viverra massa ac dui vulputate consequat. Curabitur lorem urna, ultrices sed nibh nec, auctor pellentesque mi. Cras scelerisque in enim eu lacinia. Donec commodo at orci eu interdum. Phasellus dictum risus nec ultricies mollis. Donec non imperdiet odio. Nullam eget est odio.

Aenean nec augue tellus. Nulla scelerisque lectus ipsum, non ultrices diam pretium nec. Quisque dignissim magna at eros auctor, vel sodales augue egestas. Mauris tincidunt pharetra nisl. Nunc vel turpis ut enim pharetra sollicitudin. Etiam finibus erat elit, nec bibendum justo placerat quis. Morbi molestie justo augue, a porta nulla semper et. Ut tempor sagittis enim aliquet egestas. Duis tincidunt tempus arcu eget sodales. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus ac eleifend lectus. Pellentesque sit amet dictum ligula, vel venenatis ex. Aliquam quis arcu ut sapien dictum scelerisque quis sit amet metus. Nam fringilla massa sed magna posuere, tincidunt dapibus dolor cursus. Duis ac sollicitudin nisl.

In porta ante eu massa fermentum, et blandit nisi interdum. Praesent dapibus quis quam id tempor. Nam porta venenatis consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin euismod, sapien vitae vehicula posuere, ipsum dui pretium lorem, vitae auctor mi felis ut ante. Vivamus venenatis velit sed suscipit porttitor. Aliquam sapien est, sodales sit amet est in, egestas lobortis mauris. Vivamus hendrerit libero at vestibulum mattis. Maecenas venenatis eleifend pulvinar. Cras vitae mi consequat, dapibus dui ac, bibendum diam. Donec pretium sagittis elit eget lobortis. Sed sit amet turpis leo.

Aenean varius porttitor augue, tempus suscipit odio consectetur quis. Cras in augue id lacus congue volutpat. Morbi et congue lectus. Integer tincidunt turpis mi, in bibendum purus rhoncus eget. Phasellus vitae suscipit dui, et vulputate libero. Ut sed enim hendrerit, blandit mauris nec, ultrices diam. Curabitur libero metus, consectetur rutrum blandit sed, sodales ac sem. Etiam sodales nisl eu sollicitudin iaculis. Aenean viverra auctor felis et congue. Quisque molestie est vitae erat viverra luctus.

Maecenas condimentum neque urna, ac dignissim nisl commodo ultrices. Nunc vel dictum metus. Etiam lorem justo, vulputate non leo vitae, laoreet eleifend dui. Quisque fermentum quam ac enim elementum commodo. Phasellus et malesuada lorem. Quisque commodo nisl ac tincidunt molestie. Morbi lacus leo, tincidunt quis fringilla faucibus, facilisis nec tellus. Pellentesque malesuada luctus eros, eget tempor lorem congue non. Phasellus libero odio, vulputate in diam ac, pretium eleifend diam. Cras a fermentum diam. Phasellus non elementum augue. Quisque ornare pellentesque ante in fringilla. Mauris tempor in tellus a gravida. Etiam bibendum, nulla blandit sagittis eleifend, diam nisi vestibulum lacus, non consequat massa ante non massa. Vivamus at auctor augue. Vestibulum vel sapien arcu.

Cras ornare ornare felis id sollicitudin. Pellentesque fringilla lacinia consectetur. Duis sollicitudin, erat et facilisis fermentum, ex quam facilisis justo, rutrum viverra dolor nisl eget velit. Duis ac nunc dictum, aliquet diam et, dignissim lacus. Suspendisse nec cursus lacus. Vestibulum mollis, leo a ornare semper, nunc lacus accumsan mauris, vitae laoreet eros elit vitae odio. Integer et odio tempor, suscipit purus in, efficitur lacus. Nunc nulla elit, tincidunt nec pulvinar nec, pellentesque et leo.

Morbi posuere eget erat eu fermentum. Donec dui leo, sollicitudin eu dolor eu, fermentum ornare mauris. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus dictum sem sed imperdiet varius. Vivamus vel ipsum vel orci ornare ultrices. Mauris sed fringilla nisi, sit amet maximus mauris. Sed suscipit ultricies justo, id scelerisque purus blandit non. Duis faucibus vel ligula vel luctus. In vulputate vulputate lectus quis cursus. Aliquam erat volutpat. Fusce posuere augue sit amet massa fringilla, at convallis dolor condimentum. Cras eu varius purus. Curabitur congue nisi et erat consequat auctor.

Quisque vulputate dapibus ex eget faucibus. Ut mattis sem nec porttitor faucibus. In in elementum dolor. Praesent metus justo, cursus quis odio non, blandit viverra dolor. Vestibulum at mauris quis neque vulputate laoreet eget pretium arcu. Fusce et ex eget elit placerat hendrerit at non metus. Etiam dignissim maximus arcu ac sodales. Duis at semper leo, eget volutpat metus. Aliquam ut felis enim. Vivamus sem tortor, varius vitae sem facilisis, ullamcorper tincidunt leo.

Aliquam erat volutpat. In eu tellus est. Nulla ut vulputate erat. Proin suscipit facilisis feugiat. Sed diam nisl, maximus id elit nec, tincidunt dapibus urna. Nullam eu tellus nisi. Nam in vulputate tortor. Quisque ullamcorper nisi lacus, a aliquam massa fermentum id. Pellentesque a suscipit nisl. Quisque fringilla, leo non facilisis elementum, purus nisl vestibulum nibh, in malesuada justo libero id orci. Nulla ultrices dignissim leo, sit amet congue ipsum consectetur quis. Nam sagittis, mauris id efficitur egestas, diam lorem laoreet lacus, vitae fermentum nisi tellus vel est. Cras fermentum dignissim sem sed iaculis. Nulla felis ligula, accumsan nec vestibulum in, faucibus eu urna. Curabitur non placerat purus, elementum auctor lorem.

Cras vitae lacus arcu. Nulla tristique velit ex, id varius est dapibus eget. Phasellus vehicula ex ac ligula facilisis facilisis. Mauris euismod purus id velit pretium sodales sit amet a nulla. Praesent tincidunt tempus tristique. Cras posuere id eros nec congue. Nam quam magna, vehicula ut accumsan sed, dignissim vitae leo. Nunc ut condimentum nunc.

Ut mollis sit amet lacus ac tincidunt. Sed et pulvinar quam. Fusce porttitor est vel enim scelerisque pretium. Aliquam erat volutpat. Ut nec mauris sem. Nullam convallis augue eleifend metus congue, at molestie lorem lacinia. Mauris ornare velit eget nulla dignissim aliquet. Sed ultrices et nisl a posuere. Nullam non elementum dolor. Ut vestibulum purus id pellentesque ornare. Aliquam erat volutpat. Aenean sed erat et odio ultrices condimentum in id nisl.

Nunc aliquet nulla neque, gravida ullamcorper turpis convallis at. Donec vel sapien in libero vehicula tincidunt. Morbi congue, sapien eu egestas fermentum, odio turpis mollis nisl, ac eleifend risus orci ut enim. Nullam vel ex pulvinar, blandit nisi sed, faucibus augue. Nam vel sodales mauris, eu interdum ligula. Vestibulum malesuada felis vel ex viverra ullamcorper. Nulla molestie, dolor ut sagittis auctor, neque neque tempus enim, at sagittis lorem risus sit amet est. Ut in nisi quis turpis tempor fringilla. Pellentesque faucibus purus non leo accumsan facilisis.

Vivamus scelerisque fermentum nunc, vitae scelerisque augue. Proin non imperdiet ligula, et fermentum metus. Sed tristique metus ligula, vitae mollis ante maximus quis. Nulla facilisi. Suspendisse ultrices semper velit, sit amet vehicula ante condimentum et. Phasellus dapibus lorem nec ex egestas, at pellentesque enim vestibulum. Vestibulum pretium dapibus augue eget tempor. Fusce sodales nulla vitae tellus molestie sagittis. Donec tristique gravida posuere.

Proin nec quam elit. Mauris tellus massa, consectetur id arcu sit amet, tristique ornare arcu. Pellentesque ornare porttitor nunc vitae tincidunt. In ultricies imperdiet lectus at ornare. Donec ut fermentum mauris. Quisque lobortis fringilla diam, eget varius ex vehicula sed. In non tortor lacinia, venenatis libero eu, pretium eros. Proin vel mauris et magna dapibus molestie. Quisque quis pulvinar urna. In hac habitasse platea dictumst. Pellentesque convallis interdum sollicitudin. Etiam faucibus metus a nibh vestibulum fermentum. Donec fringilla vehicula tristique. Nunc interdum posuere sapien. Etiam aliquet, ipsum et tincidunt cursus, metus erat sollicitudin dui, in laoreet nisl libero eleifend lacus.

Suspendisse sed velit nunc. Aliquam erat volutpat. Proin finibus odio nec magna rutrum, congue facilisis risus ultricies. Donec euismod vulputate ullamcorper. Integer sagittis egestas leo. Etiam mollis euismod libero, in rutrum nunc fermentum ac. Etiam egestas lectus nec magna convallis, quis elementum augue dignissim. Praesent non egestas nibh, eget dictum tortor. Curabitur vehicula lorem justo, a aliquam erat gravida non.

Suspendisse volutpat, eros a vulputate dictum, ante libero blandit nulla, non eleifend mi turpis eget mi. Maecenas pretium, neque id rhoncus fringilla, leo dui feugiat nisi, sit amet aliquet erat lacus sit amet turpis. Suspendisse vitae malesuada elit. Vestibulum sit amet vulputate tellus, vel aliquam nisl. Curabitur nec gravida felis. Aliquam in pharetra elit. Morbi faucibus elit non nunc hendrerit porttitor. Quisque vitae consectetur est. Nam eget nunc a quam laoreet porttitor. Morbi ex augue, tempus a ipsum accumsan, tincidunt auctor tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla at nibh faucibus, laoreet est at, porta odio. Ut lobortis urna in dignissim imperdiet. Donec egestas dui quam, vel imperdiet tortor sagittis nec.</p>
    </div>
  )
}
export default About;
